version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_DB: esp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin 
    depends_on:
      - postgres

  web:
    build: ./app
    container_name: esp_webapp
    ports:
      - "5000:5000"
    depends_on:
      - postgres

volumes:
  pgdata:
  pgadmin_data: